const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
    patientUsername: String,
    therapistUsername: String,
    patientName: String,
    reportType: { 
        type: String, 
        enum: ['manual', 'voice_analysis'], 
        default: 'manual' 
    },
    emotion: String,
    analysisData: Object,
    fileName: String,
    pdfData: String,
    sentAt: { 
        type: Date, 
        default: Date.now 
    },
    isRead: { 
        type: Boolean, 
        default: false 
    },
    isAutoGenerated: { 
        type: Boolean, 
        default: false 
    },
    emotionalAnalysis: {
        emotion: String,
        confidence: Number,
        analysisDate: Date
    },
    recommendations: [String],
    createdAt: {
        type: Date,
        default: Date.now
    },
    status: {
        type: String,
        enum: ['draft', 'submitted', 'reviewed'],
        default: 'draft'
    }
});

module.exports = mongoose.model('Report', reportSchema);